"""Add transmission_type field to Candidate model

Revision ID: 0b5db40a5ef3
Revises: b547ea531bbe
Create Date: 2025-10-05 17:36:55.119617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5db40a5ef3'
down_revision = 'b547ea531bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('transmission_type')

    # ### end Alembic commands ###
