"""Add permesso di soggiorno fields

Revision ID: 12c944d9f3f7
Revises: aa2a7381caa1
Create Date: 2025-10-05 16:04:15.343600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c944d9f3f7'
down_revision = 'aa2a7381caa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permesso_tipo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('permesso_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('permesso_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('permesso_questura', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('permesso_questura')
        batch_op.drop_column('permesso_expiry_date')
        batch_op.drop_column('permesso_issue_date')
        batch_op.drop_column('permesso_tipo')

    # ### end Alembic commands ###
