"""Rename other_location to city_availability

Revision ID: 16651b4495b8
Revises: 9716bc779600
Create Date: 2025-07-21 11:49:09.979116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16651b4495b8'
down_revision = '9716bc779600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_availability', sa.String(length=64), nullable=True))
        batch_op.drop_column('other_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_location', sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_column('city_availability')

    # ### end Alembic commands ###
