"""Add has_children field to candidate model

Revision ID: 1f74bd555442
Revises: ced253ef5c18
Create Date: 2025-10-05 18:00:21.297290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f74bd555442'
down_revision = 'ced253ef5c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_children', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('has_children')

    # ### end Alembic commands ###
