"""Add privacy policy settings to DynamicForm

Revision ID: 31cfb0b864a4
Revises: 47b5ae781403
Create Date: 2025-07-22 10:20:45.047264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cfb0b864a4'
down_revision = '47b5ae781403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_policy_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('privacy_policy_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('privacy_policy_text', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('privacy_policy_new_tab', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.drop_column('privacy_policy_new_tab')
        batch_op.drop_column('privacy_policy_text')
        batch_op.drop_column('privacy_policy_url')
        batch_op.drop_column('privacy_policy_enabled')

    # ### end Alembic commands ###
