"""Aggiungi campi categoria e sottocategoria ai form dinamici

Revision ID: 47b5ae781403
Revises: ac9374397ec5
Create Date: 2025-07-21 12:15:51.915057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b5ae781403'
down_revision = 'ac9374397ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.drop_column('subcategory')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
