"""empty message

Revision ID: 5e2b69422dac
Revises: 73537abe40c1
Create Date: 2025-07-26 14:15:57.291274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '5e2b69422dac'
down_revision = '73537abe40c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_link_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_link_token'))

    op.drop_table('share_link')
    # ### end Alembic commands ###
