"""Add codice_fiscale and permesso_soggiorno fields

Revision ID: 67ab71335f06
Revises: 65ab218dea47
Create Date: 2025-07-21 10:53:53.762678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ab71335f06'
down_revision = '65ab218dea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codice_fiscale', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('permesso_soggiorno', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('permesso_soggiorno')
        batch_op.drop_column('codice_fiscale')

    # ### end Alembic commands ###
