"""empty message

Revision ID: 73537abe40c1
Revises: 30d87206db3c
Create Date: 2025-07-24 14:54:13.304951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73537abe40c1'
down_revision = '30d87206db3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.String(length=256), nullable=True),
    sa.Column('setting_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
