"""empty message

Revision ID: 9716bc779600
Revises: 5afc829fc62b
Create Date: 2025-07-21 11:26:35.696417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9716bc779600'
down_revision = '5afc829fc62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('availability_till', sa.Date(), nullable=True))
        batch_op.drop_column('availability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_column('availability_till')
        batch_op.drop_column('availability_from')

    # ### end Alembic commands ###
