"""Add international license fields

Revision ID: 990ad4312283
Revises: d73b728d8704
Create Date: 2025-10-05 17:04:30.725982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990ad4312283'
down_revision = 'd73b728d8704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('international_license', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('international_license_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('international_license_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('international_license_expiry')
        batch_op.drop_column('international_license_number')
        batch_op.drop_column('international_license')

    # ### end Alembic commands ###
