"""first push

Revision ID: 9f9c3ec4ede4
Revises: 
Create Date: 2025-06-09 17:46:03.655993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9c3ec4ede4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=64), nullable=False),
    sa.Column('nationality', sa.String(length=32), nullable=False),
    sa.Column('marital_status', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('tshirt_size', sa.String(length=8), nullable=True),
    sa.Column('shoe_size_eu', sa.String(length=8), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('country_of_residence', sa.String(length=32), nullable=True),
    sa.Column('id_document', sa.String(length=32), nullable=True),
    sa.Column('id_number', sa.String(length=64), nullable=True),
    sa.Column('id_expiry_date', sa.Date(), nullable=True),
    sa.Column('id_country', sa.String(length=32), nullable=True),
    sa.Column('license_country', sa.String(length=32), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('license_category', sa.String(length=16), nullable=True),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('years_driving_experience', sa.Integer(), nullable=True),
    sa.Column('auto_moto_munito', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('other_experience', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=64), nullable=True),
    sa.Column('other_location', sa.String(length=64), nullable=True),
    sa.Column('language_1', sa.String(length=32), nullable=True),
    sa.Column('proficiency_1', sa.String(length=16), nullable=True),
    sa.Column('language_2', sa.String(length=32), nullable=True),
    sa.Column('proficiency_2', sa.String(length=16), nullable=True),
    sa.Column('language_3', sa.String(length=32), nullable=True),
    sa.Column('proficiency_3', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('curriculum')
    op.drop_table('user')
    op.drop_table('candidate')
    # ### end Alembic commands ###
