"""Add domicile fields to Candidate model

Revision ID: aa2a7381caa1
Revises: 3791b37930c9
Create Date: 2025-10-05 15:47:29.691367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'aa2a7381caa1'
down_revision = '3791b37930c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('w3_email_logs')
    op.drop_table('w3_users')
    op.drop_table('w3_orders')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domicile_address', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('domicile_city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('domicile_postal_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('domicile_country', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('domicile_country')
        batch_op.drop_column('domicile_postal_code')
        batch_op.drop_column('domicile_city')
        batch_op.drop_column('domicile_address')

    op.create_table('w3_orders',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('departure_port', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('arrival_port', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('pending')"), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__w3_order__3213E83F6DDCCCE7')
    )
    op.create_table('w3_users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('role', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('user')"), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__w3_users__3213E83F59B2E9AD')
    )
    op.create_table('w3_email_logs',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('subject', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('sender', sa.NVARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('received_date', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('processed', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(getutcdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__w3_email__3213E83FE2FB44D9')
    )
    # ### end Alembic commands ###
