"""Change international_license to Boolean

Revision ID: b547ea531bbe
Revises: 990ad4312283
Create Date: 2025-10-05 17:18:37.186862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b547ea531bbe'
down_revision = '990ad4312283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('international_license',
               existing_type=sa.VARCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('international_license',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
