"""Add work_away_from_domicile field to Candidate model

Revision ID: ced253ef5c18
Revises: 0b5db40a5ef3
Create Date: 2025-10-05 17:48:23.810730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced253ef5c18'
down_revision = '0b5db40a5ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_away_from_domicile', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('work_away_from_domicile')

    # ### end Alembic commands ###
