"""Remove unused permesso soggiorno fields

Revision ID: d73b728d8704
Revises: db6961cfba4d
Create Date: 2025-10-05 16:50:09.223319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73b728d8704'
down_revision = 'db6961cfba4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('permesso_tipo')
        batch_op.drop_column('permesso_questura')
        batch_op.drop_column('permesso_issue_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permesso_issue_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permesso_questura', sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permesso_tipo', sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
