"""Add instagram field to candidate model

Revision ID: f1f16559bce8
Revises: 1f74bd555442
Create Date: 2025-10-05 18:04:01.964639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f16559bce8'
down_revision = '1f74bd555442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('instagram')

    # ### end Alembic commands ###
